# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aegis.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x61\x65gis.proto\x12\x05\x61\x65gis\"\x14\n\x12HealthCheckRequest\"\x8b\x01\n\x13HealthCheckResponse\x12\x38\n\x06status\x18\x01 \x01(\x0e\x32(.aegis.HealthCheckResponse.ServingStatus\":\n\rServingStatus\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0b\n\x07SERVING\x10\x01\x12\x0f\n\x0bNOT_SERVING\x10\x02\"\xa3\x01\n\x0c\x41\x65gisRequest\x12\x19\n\x11\x65ncrypted_payload\x18\x01 \x01(\x0c\x12\x33\n\x08metadata\x18\x02 \x03(\x0b\x32!.aegis.AegisRequest.MetadataEntry\x12\x12\n\npublic_key\x18\x03 \x01(\x0c\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\xab\x01\n\rAegisResponse\x12\x18\n\x10\x66\x61ke_http_status\x18\x01 \x01(\x05\x12\x19\n\x11\x65ncrypted_payload\x18\x02 \x01(\x0c\x12\x34\n\x08metadata\x18\x03 \x03(\x0b\x32\".aegis.AegisResponse.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x32\x8a\x01\n\x0c\x41\x65gisGateway\x12\x34\n\x07Process\x12\x13.aegis.AegisRequest\x1a\x14.aegis.AegisResponse\x12\x44\n\x0bHealthCheck\x12\x19.aegis.HealthCheckRequest\x1a\x1a.aegis.HealthCheckResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aegis_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_AEGISREQUEST_METADATAENTRY']._options = None
  _globals['_AEGISREQUEST_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_AEGISRESPONSE_METADATAENTRY']._options = None
  _globals['_AEGISRESPONSE_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_HEALTHCHECKREQUEST']._serialized_start=22
  _globals['_HEALTHCHECKREQUEST']._serialized_end=42
  _globals['_HEALTHCHECKRESPONSE']._serialized_start=45
  _globals['_HEALTHCHECKRESPONSE']._serialized_end=184
  _globals['_HEALTHCHECKRESPONSE_SERVINGSTATUS']._serialized_start=126
  _globals['_HEALTHCHECKRESPONSE_SERVINGSTATUS']._serialized_end=184
  _globals['_AEGISREQUEST']._serialized_start=187
  _globals['_AEGISREQUEST']._serialized_end=350
  _globals['_AEGISREQUEST_METADATAENTRY']._serialized_start=303
  _globals['_AEGISREQUEST_METADATAENTRY']._serialized_end=350
  _globals['_AEGISRESPONSE']._serialized_start=353
  _globals['_AEGISRESPONSE']._serialized_end=524
  _globals['_AEGISRESPONSE_METADATAENTRY']._serialized_start=303
  _globals['_AEGISRESPONSE_METADATAENTRY']._serialized_end=350
  _globals['_AEGISGATEWAY']._serialized_start=527
  _globals['_AEGISGATEWAY']._serialized_end=665
# @@protoc_insertion_point(module_scope)
